In [ ]:
import pandas as pd

In [ ]:
from sklearn.impute import KNNImputer

In [ ]:
import numpy as np

In [ ]:
X = [ [3, np.NaN, 5], [1, 0, 0], [3, 3, 3],[3, 5, 3]  ]


In [ ]:
print(pd.DataFrame(X))

   0    1  2
0  3  NaN  5
1  1  0.0  0
2  3  3.0  3
3  3  5.0  3


In [ ]:
imputer = KNNImputer(n_neighbors=1)

In [ ]:
impute_with_1 = imputer.fit_transform(X)

In [ ]:
print("\n Imput with 1 neighbor \n", impute_with_1)


 Imput with 1 neighbor 
 [[3. 3. 5.]
 [1. 0. 0.]
 [3. 3. 3.]
 [3. 5. 3.]]


In [ ]:
imputer = KNNImputer(n_neighbors=2)
impute_with_2 = imputer.fit_transform(X)
print("\n Imput with 2 neighbor \n", impute_with_2)


 Imput with 2 neighbor 
 [[3. 4. 5.]
 [1. 0. 0.]
 [3. 3. 3.]
 [3. 5. 3.]]


In [ ]:
X_categorical = [['naji', 10, 'male'], ['nicky', 15, 'male'], ['july', 15, None],['feni', 12, 'female'], ['johny', 9, 'male']]

In [ ]:
print(pd.DataFrame(X_categorical))

       0   1       2
0   naji  10    male
1  nicky  15    male
2   july  15    None
3   feni  12  female
4  johny   9    male


In [ ]:
df = pd.DataFrame(X_categorical, columns=['Name', 'Age', 'Gender'])

In [ ]:
df["GenderMap"] = df.Gender.map({'female': 1, 'male': 0})

In [ ]:
df

Name  Age  Gender  GenderMap
0   naji   10    male        0.0
1  nicky   15    male        0.0
2   july   15    None        NaN
3   feni   12  female        1.0
4  johny    9    male        0.0

In [ ]:
imputer = KNNImputer(n_neighbors=2)
df_filled = imputer.fit_transform(df[['GenderMap']])

In [ ]:
df_filled

array([[0.  ],
       [0.  ],
       [0.25],
       [1.  ],
       [0.  ]])